// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SzaboGlass.Data;

#nullable disable

namespace SzaboGlass.Data.Migrations
{
    [DbContext(typeof(Program))]
    [Migration("20240829173035_GlassRefactor")]
    partial class GlassRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("SzaboGlass.Data.Entity.Glass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PurchasePriceCE")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PurchasePriceMalyi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GlassTypeId");

                    b.ToTable("Glasses");
                });

            modelBuilder.Entity("SzaboGlass.Data.Entity.GlassType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GlassTypes");
                });

            modelBuilder.Entity("SzaboGlass.Data.Entity.Glass", b =>
                {
                    b.HasOne("SzaboGlass.Data.Entity.GlassType", "GlassType")
                        .WithMany()
                        .HasForeignKey("GlassTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlassType");
                });
#pragma warning restore 612, 618
        }
    }
}
